# .github/workflows/ci-cd.yml
on:
  push:
    tags:
      - v*
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pozo
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - run: python3 -m pip install --upgrade pip setuptools wheel build
    - run: python3 -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
